### ISSUE TITLE
Read trees from URLs

### ISSUE THREAD

**Issue by Wytamma** [clockor2/phylojs#27]
We should handle reading trees from urls. Not sure what the API should be though...

**Comment by LeoFeatherstone** [comment]
I have added an example for how to do this with a fetch request in #63

**Comment by Wytamma** [comment]
This issue was about adding a feature to do this internally if a URL is passed. Currently PhyloJS will raise an error is some that looks like a URL is passed -> https://github.com/clockor2/phylojs/blob/main/src/io/readers/tree.ts#L19
