### ISSUE TITLE
readNewick fails to read egTree

### ISSUE THREAD

**Issue by Wytamma** [clockor2/phylojs#58]
When i try to read `https://raw.githubusercontent.com/clockor2/phylojs/main/test/data/egTree.nwk` phyloJS returns a tree with a single node. 

```javascript
let tree = phylojs.readNewick(newick)
console.log(tree)
```
"'t2_2005':0.0008076102;"

**Comment by Wytamma** [comment]
@LeoFeatherstone I created a branch https://github.com/clockor2/phylojs/tree/read-tree-bug-%2358 to work on this issue and added a test for the case that is failing.

**Comment by LeoFeatherstone** [comment]
I think the file you're trying to read from has multiple trees in it separated by newline characters

**Comment by LeoFeatherstone** [comment]
Are yo happy with this fix @Wytamma ?

**Comment by Wytamma** [comment]
Shouldn’t read tree just return the first tree or error?
