### ISSUE TITLE
Why Do You Claim That This Could Be Used In Typescript?

### ISSUE THREAD

**Issue by uncle-yi** [clockor2/phylojs#69]
All your examples included PhylocanvasGL, and this can only be used on javascript, yet you claim that this can be used on typescript, i would be very pleased to know that why you think this could be run on TS??

**Comment by Wytamma** [comment]
Hey @uncle-yi and anyone else looking for similar issues. 

You can 100% use PhylocanvasGL and any other JavaScript library in a TypeScript project. You just need to define the types for that library. You can see an [example](https://github.com/clockor2/clockor2/blob/main/src/decs.d.ts#L1) of this in our project Clockor2 which is a TypeScript project that uses both PhylocanvasGL and Phylojs.

Additionally, as stated in the first line of the [README](https://github.com/clockor2/phylojs/blob/main/README.md?plain=1#L20) Phylojs is "javascript/typescript library for manipulating phylogenetic trees".

**Comment by yilitai** [comment]
@Wytamma thank you for the explanation, I m new to js and ts. I have tried using PhylocanvasGL in typescript Vue but I just cant build it right. But I have render the tree with d3 myself, so all works out.
